wiki(){
  vim -c VimwikiIndex
  source activate py35
  vim -c VimwikiIndex -c VimwikiAll2HTML -c q 
  source deactivate
}

wiki_html(){
  sudo google-chrome-stable ${HOME}/Dropbox/wiki/html/index.html --no-sandbox >/dev/null 2>&1
}

wiki_cd(){
  cd ${HOME}/Dropbox/wiki/markdown
}
