" Vimwiki
set nocompatible
filetype plugin on
syntax on
let g:vimwiki_list = [{'path': '$HOME/Dropbox/wiki/markdown',
                      \"path_html": "$HOME/Dropbox/wiki/html/",
                      \"syntax": "markdown", 
                      \"ext": ".md",
                      \"css_file": "$HOME/Dropbox/wiki/templates/markdown.css",
                      \'custom_wiki2html': '$HOME/Dropbox/wiki/scripts/vimwiki_markdown.py',
                      \'template_path': '$HOME/Dropbox/wiki/templates',
                      \'template_default': 'default',
                      \'template_ext': '.html',
                      \"auto_export": 0}]
let g:vimwiki_ext = '.md' " set extension to .md
let g:vimwiki_global_ext = 0 " make sure vimwiki doesn't own all .md files
let g:vimwiki_use_mouse = 1
let g:vimwiki_markdown_link_ext = 1

" Automatically clean the unused html
" https://www.reddit.com/r/vim/comments/766cgb/vimwiki_automaticly_remove_unused_html_files/
function! VimwikiDeleteClean()
  let htmlfile = expand('%:r') . '.html'
  lcd ${HOME}/Dropbox/wiki/html/
  call delete(htmlfile)
  lcd %:p:h
  call vimwiki#base#delete_link()
endfunction
autocmd filetype vimwiki nnoremap <buffer> <leader>wd :call VimwikiDeleteClean()<CR>

" TimeStamp
map <F4> :r! date +"\%Y-\%m-\%d \%H:\%M:\%S"<cr>

" disable the <tab> mapping provided by vimwiki, which interferes with SuperTab
let g:vimwiki_table_mappings = 0

set tabstop=4     " (ts) width (in spaces) that a <tab> is displayed as
